import type { CareerCategory } from '../types';

export const EXPLORE_CAREERS: CareerCategory[] = [
  {
    name: 'Information Technology & Digital Careers',
    icon: 'Code',
    careers: [
      { name: 'Software Engineer / Developer', path: 'software-engineer' },
      { name: 'Web Developer / Mobile App Developer', path: 'web-mobile-developer' },
      { name: 'UI/UX Designer', path: 'ui-ux-designer' },
      { name: 'Data Analyst / Data Scientist', path: 'data-scientist' },
      { name: 'Network Engineer', path: 'network-engineer' },
      { name: 'Cybersecurity Specialist', path: 'cybersecurity-specialist' },
      { name: 'Cloud Engineer / DevOps Engineer', path: 'cloud-devops-engineer' },
      { name: 'IT Project Manager', path: 'it-project-manager' },
      { name: 'Game Developer', path: 'game-developer' },
      { name: 'AI / Machine Learning Engineer', path: 'ai-ml-engineer' },
      { name: 'Data Engineer', path: 'data-engineer' },
      { name: 'Database Administrator', path: 'database-administrator' },
      { name: 'IT Support Specialist', path: 'it-support-specialist' },
      { name: 'Quality Assurance Analyst', path: 'quality-assurance-analyst' },
    ],
  },
  {
    name: 'Business, Management & Finance',
    icon: 'TrendingUp',
    careers: [
      { name: 'Accountant / Auditor', path: 'accountant' },
      { name: 'Banker / Financial Analyst', path: 'banker-financial-analyst' },
      { name: 'Business Analyst', path: 'business-analyst' },
      { name: 'Marketing Executive / Brand Manager', path: 'marketing-manager' },
      { name: 'HR Manager', path: 'hr-manager' },
      { name: 'Project Coordinator', path: 'project-coordinator' },
      { name: 'Supply Chain Manager', path: 'supply-chain-manager' },
      { name: 'Entrepreneur / Startup Founder', path: 'entrepreneur' },
      { name: 'Investment Banker', path: 'investment-banker' },
      { name: 'Business Consultant', path: 'business-consultant' },
      { name: 'Business Development Manager', path: 'business-development-manager' },
      { name: 'Actuarial Science', path: 'actuarial-science' },
    ],
  },
  {
    name: 'Education & Training',
    icon: 'GraduationCap',
    careers: [
      { name: 'Teacher / Lecturer', path: 'teacher' },
      { name: 'Education Consultant', path: 'education-consultant' },
      { name: 'Curriculum Developer', path: 'curriculum-developer' },
      { name: 'Online Tutor / EdTech Content Creator', path: 'online-tutor' },
      { name: 'School Administrator', path: 'school-administrator' },
    ],
  },
  {
    name: 'Healthcare & Medical Fields',
    icon: 'Heart',
    careers: [
      { name: 'Doctor / Surgeon', path: 'doctor' },
      { name: 'Nurse / Midwife', path: 'nurse' },
      { name: 'Pharmacist', path: 'pharmacist' },
      { name: 'Medical Laboratory Technologist', path: 'medical-lab-technologist' },
      { name: 'Physiotherapist', path: 'physiotherapist' },
      { name: 'Nutritionist / Dietitian', path: 'nutritionist' },
      { name: 'Psychologist / Counselor', path: 'psychologist' },
    ],
  },
  {
    name: 'Engineering & Technical',
    icon: 'Cog',
    careers: [
      { name: 'Civil Engineer', path: 'civil-engineer' },
      { name: 'Mechanical Engineer', path: 'mechanical-engineer' },
      { name: 'Electrical Engineer', path: 'electrical-engineer' },
      { name: 'Electronic & Telecommunication Engineer', path: 'electronic-telecom-engineer' },
      { name: 'Mechatronics / Robotics Engineer', path: 'mechatronics-engineer' },
      { name: 'Quantity Surveyor', path: 'quantity-surveyor' },
      { name: 'Architect', path: 'architect' },
      { name: 'Draughtsman', path: 'draughtsman' },
      { name: 'Technician', path: 'technician' },
    ],
  },
  {
    name: 'Tourism, Hospitality & Travel',
    icon: 'Briefcase',
    careers: [
      { name: 'Hotel Manager', path: 'hotel-manager' },
      { name: 'Tour Guide', path: 'tour-guide' },
      { name: 'Travel Consultant', path: 'travel-consultant' },
      { name: 'Chef / Culinary Specialist', path: 'chef' },
      { name: 'Event Planner', path: 'event-planner' },
      { name: 'Airline Crew / Aviation Officer', path: 'airline-crew' },
    ],
  },
  {
    name: 'Media, Communication & Design',
    icon: 'Megaphone',
    careers: [
      { name: 'Journalist / News Reporter', path: 'journalist' },
      { name: 'Photographer / Videographer', path: 'photographer-videographer' },
      { name: 'Graphic Designer', path: 'graphic-designer' },
      { name: 'Content Creator / Influencer', path: 'content-creator' },
      { name: 'Social Media Manager', path: 'social-media-manager' },
      { name: 'Film Director / Editor', path: 'film-director-editor' },
      { name: 'Animator / Motion Designer', path: 'animator' },
      { name: 'Creative Director', path: 'creative-director' },
      { name: 'Product Designer', path: 'product-designer' },
    ],
  },
  {
    name: 'Agriculture, Environment & Sustainability',
    icon: 'Leaf',
    careers: [
      { name: 'Agricultural Officer', path: 'agricultural-officer' },
      { name: 'Environmental Scientist', path: 'environmental-scientist' },
      { name: 'Forestry / Wildlife Officer', path: 'forestry-wildlife-officer' },
      { name: 'Agribusiness Entrepreneur', path: 'agribusiness-entrepreneur' },
      { name: 'Renewable Energy Specialist', path: 'renewable-energy-specialist' },
    ],
  },
  {
    name: 'Law, Governance & Public Service',
    icon: 'Scale',
    careers: [
      { name: 'Lawyer / Attorney-at-law', path: 'lawyer' },
      { name: 'Legal Advisor', path: 'legal-advisor' },
      { name: 'Police Officer', path: 'police-officer' },
      { name: 'Government Officer (Administrative Service, Foreign Service, etc.)', path: 'government-officer' },
      { name: 'Politician / Policy Analyst', path: 'politician-policy-analyst' },
    ],
  },
  {
    name: 'Skilled Trades & Vocational Paths',
    icon: 'Cog',
    careers: [
      { name: 'Electrician', path: 'electrician' },
      { name: 'Carpenter', path: 'carpenter' },
      { name: 'Plumber', path: 'plumber' },
      { name: 'Welder / Mechanic', path: 'welder-mechanic' },
      { name: 'Tailor / Fashion Designer', path: 'fashion-designer' },
      { name: 'Beautician / Hairdresser', path: 'beautician' },
      { name: 'Vehicle Technician', path: 'vehicle-technician' },
    ],
  },
  {
    name: 'Freelance, Remote & Creative Economy',
    icon: 'Lightbulb',
    careers: [
      { name: 'Freelancer (Developer / Designer / Writer)', path: 'freelancer' },
      { name: 'Digital Marketer', path: 'digital-marketer' },
      { name: 'YouTuber / Podcaster', path: 'youtuber-podcaster' },
      { name: 'eCommerce Seller', path: 'ecommerce-seller' },
      { name: 'Virtual Assistant', path: 'virtual-assistant' },
    ],
  },
  {
    name: 'Emerging & Future Careers',
    icon: 'Target',
    careers: [
      { name: 'AI Researcher', path: 'ai-researcher' },
      { name: 'Blockchain Developer', path: 'blockchain-developer' },
      { name: 'Renewable Energy Engineer', path: 'renewable-energy-engineer' },
      { name: 'Drone Operator', path: 'drone-operator' },
      { name: 'Cybersecurity Analyst', path: 'cybersecurity-analyst' },
      { name: 'Data Ethics Officer', path: 'data-ethics-officer' },
      { name: 'AR/VR Developer', path: 'ar-vr-developer' },
      { name: 'Research Scientist', path: 'research-scientist' },
    ],
  },
];


export const COMMON_CAREER_PATHS = [
  { name: 'Software Engineer', path: 'software-engineer', icon: 'Code' },
  { name: 'Doctor', path: 'doctor', icon: 'Heart' },
  { name: 'Accountant', path: 'accountant', icon: 'Briefcase' },
  { name: 'Civil Engineer', path: 'civil-engineer', icon: 'Cog' },
  { name: 'Marketing Manager', path: 'marketing-manager', icon: 'Megaphone' },
  { name: 'Graphic Designer', path: 'graphic-designer', icon: 'Palette' },
  { name: 'Lawyer', path: 'lawyer', icon: 'Scale' },
  { name: 'Teacher', path: 'teacher', icon: 'Book' },
  { name: 'Data Scientist', path: 'data-scientist', icon: 'Code' },
  { name: 'Nurse', path: 'nurse', icon: 'Heart' },
  { name: 'Architect', path: 'architect', icon: 'Cog' },
  { name: 'Hotel Manager', path: 'hotel-manager', icon: 'Briefcase' },
  { name: 'Chef', path: 'chef', icon: 'Briefcase' },
  { name: 'Psychologist', path: 'psychologist', icon: 'Heart' },
  { name: 'HR Manager', path: 'hr-manager', icon: 'Briefcase' },
  { name: 'Pharmacist', path: 'pharmacist', icon: 'Heart' },
  { name: 'Mechanical Engineer', path: 'mechanical-engineer', icon: 'Cog' },
  { name: 'Cybersecurity Specialist', path: 'cybersecurity-specialist', icon: 'Code' },
];
