# Docker Compose for Local Production Testing
version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=careerpath_lk
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ADMIN_KEY=${ADMIN_KEY}
      - CORS_ORIGIN=http://localhost:3000
    env_file:
      - .env.production

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: careerpath_lk
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
